#Requires -Version 7.2
<#
.SYNOPSIS
    Re-derive pass 0037's claims rather than reading them back.

.DESCRIPTION
    Five named checks, from the pass prompt. Nothing here reads a number out of
    the document it is checking: the scorer is run from a FRESH CLONE of the
    harness rather than from the working tree, the mutations are regenerated in
    this file rather than delegated to the driver whose report is the artifact,
    and the tf-003 rescore is reproduced by cloning and building the target
    again.

    WHY CHECKS 1 AND 2 CLONE THE HARNESS. The artifacts under
    plans/0037-consolidation/ were produced from the working tree. Running the
    same scripts from the same tree would re-derive nothing about what was
    committed; a clone is what makes "this is in the repository and it works"
    a different statement from "it worked here".

    WHY CHECK 1 REGENERATES ITS OWN MUTATIONS. Invoke-TfFixture2CaseFalsification.ps1
    produces case-scorer.txt, and asking it whether case-scorer.txt is right is
    a script agreeing with itself. Mutations 3 and 8 are rebuilt here, from the
    oracle, and the case-level outcomes asserted directly.

    Clones land under a SHORT root: the session scratchpad path is long enough
    that `git clone` dies writing a keep file, which looks exactly like a
    network fault if you have not seen it (pass 0033, and again in run 007).

.PARAMETER FailCheck
    Deliberately break one check, to prove it can fail. A verify script that has
    only ever been green is indistinguishable from one that cannot go red.

.PARAMETER SkipClone
    Skip check 3, which needs the network, a credential and a build.
#>
[CmdletBinding()]
param(
    [ValidateSet('None', '1', '2', '3', '4', '5')]
    [string] $FailCheck = 'None',
    [switch] $SkipClone
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Harness = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$Plan = $PSScriptRoot
$Ecosystem = Split-Path -Parent $Harness
$Work = 'C:\Users\jlbal\AppData\Local\Temp\p0037\verify'

$FinalSha = 'd76d16bb5083f422ccc05671e21cefde3c1a004e'
$FixtureShas = [ordered]@{
    TfSiteCore = 'a228e78c247d2d4367303f303c4363d9906e06f2'
    TfSiteEdge = '1ae66c2712f799a69304cb4364e91e4d10d694c4'
    TfSiteOps  = 'fe27a34f7585b86b6fdbf12b609e17d4cb0f4b83'
}

$results = [System.Collections.Generic.List[object]]::new()
function Add-Result {
    param([string] $Check, [bool] $Passed, [string] $Detail, [switch] $Skipped)
    $state = $Skipped ? 'SKIP' : ($Passed ? 'PASS' : 'FAIL')
    $results.Add([pscustomobject]@{ Check = $Check; Result = $state; Detail = $Detail })
    Write-Host ('  {0,-5} {1,-56} {2}' -f $state, $Check, $Detail)
}

Write-Host "`nPass 0037 verification`n"

if (Test-Path $Work) { Remove-Item $Work -Recurse -Force -ErrorAction SilentlyContinue }
$null = New-Item -ItemType Directory -Path $Work -Force

# A fresh clone of the harness at the committed tip, for checks 1, 2 and 4.
$clone = Join-Path $Work 'harness'
git clone --quiet $Harness $clone 2>&1 | Out-Null
git -C $clone checkout --quiet (git -C $Harness rev-parse HEAD).Trim() 2>&1 | Out-Null
$cloneSha = (git -C $clone rev-parse HEAD).Trim()

# ---- 1. The promoted scorer, from the clone, and its own mutations ---------
$scorer = Join-Path $clone 'evals/tf/fixture2/Test-TfFixture2Case.ps1'
$oracle = Join-Path $clone 'evals/tf/fixture2/expected-graph.json'
$mutator = Join-Path $clone 'evals/tf/Mutate-TfGraph.ps1'
$detail = @()
$ok1 = $true

if (-not (Test-Path $scorer)) {
    $ok1 = $false; $detail += 'the scorer is not in the clone'
}
else {
    # (a) the control.
    $control = & $scorer -Path $oracle
    $controlPassed = $FailCheck -eq '1' ? 6 : $control.Passed
    if ($controlPassed -ne 7) { $ok1 = $false }
    $detail += "oracle vs self $controlPassed / $($control.Total)"

    # (b) mutation 3, regenerated HERE: drop a cross-repository output
    #     reference. Case 3 must go red and no other case may.
    $doc = Get-Content -LiteralPath $oracle -Raw | ConvertFrom-Json
    $doc.graph.edges = @($doc.graph.edges | Where-Object {
            -not ($_.from -eq 'TfSiteEdge:.#output.pop_ids' -and $_.to -eq 'TfSiteOps:.#local.edge_pop_ids')
        })
    $m3 = & $scorer -GraphObject $doc
    $red = @($m3.Cases | Where-Object Result -EQ 'FAIL' | ForEach-Object { $_.Name })
    $m3Ok = @($red).Count -eq 1 -and $red[0] -like '3 cross-repository*'
    if (-not $m3Ok) { $ok1 = $false }
    $detail += ("mutation 3 -> {0} / 7, red: {1}" -f $m3.Passed, (@($red).Count ? ($red -join ' + ') : 'none'))

    # (c) mutation 8, regenerated by the mutator: the scorer must REFUSE.
    $dup = & $mutator -Path $oracle -Mutation duplicate-id -Fixture fixture2
    $refused = $false
    try { $null = & $scorer -GraphObject $dup } catch { $refused = $true }
    if (-not $refused) { $ok1 = $false }
    $detail += ("mutation 8 {0}" -f ($refused ? 'refused' : 'SCORED - not refused'))
}
Add-Result '1 promoted scorer: control, mutation 3, mutation 8' $ok1 ($detail -join '; ')

# ---- 2. Both suites, from the clone, at their pinned counts ----------------
$suiteOut = & pwsh -NoProfile -File (Join-Path $clone 'evals/tf/Invoke-TfSuite.ps1') 2>&1 | Out-String
$suiteExit = $LASTEXITCODE
$f1 = [regex]::Match($suiteOut, 'FIXTURE1: (\d+) passed, (\d+) failed')
$f2 = [regex]::Match($suiteOut, 'FIXTURE2: (\d+) passed, (\d+) failed')
$f1Ok = $f1.Success -and $f1.Groups[1].Value -eq '15' -and $f1.Groups[2].Value -eq '0'
$f2Ok = $f2.Success -and $f2.Groups[1].Value -eq '18' -and $f2.Groups[2].Value -eq '0'
if ($FailCheck -eq '2') { $f2Ok = $false }
Add-Result '2 fixture-1 at 15/15, fixture-2 at its new pin 18/18' ($f1Ok -and $f2Ok -and $suiteExit -eq 0) (
    ('{0}; {1}; suite exit {2}' -f
        ($f1.Success ? $f1.Value : 'FIXTURE1 line absent'),
        ($f2.Success ? $f2.Value : 'FIXTURE2 line absent'),
        $suiteExit))

# ---- 3. The tf-003 rescore, reproduced ------------------------------------
if ($SkipClone) {
    Add-Result '3 tf-003 rescore reproduced from a fresh built clone' $false 'skipped by request' -Skipped
}
elseif (-not $env:AZDO_PAT) {
    # Loud, never quiet: a check that cannot be contradicted must not report
    # success.
    Add-Result '3 tf-003 rescore reproduced from a fresh built clone' $false 'AZDO_PAT is not set: the fixture cannot be cloned, so this check GRADES NOTHING' -Skipped
}
else {
    $target = Join-Path $Work 'target'
    git clone --quiet --branch run-tf-003-generalisation https://github.com/JerryBalmer1/PSTerraformGraph.git $target 2>&1 | Out-Null
    $targetSha = (git -C $target rev-parse HEAD).Trim()

    foreach ($name in $FixtureShas.Keys) {
        $dest = Join-Path $Work $name
        $env:GIT_CONFIG_COUNT = '1'
        $env:GIT_CONFIG_KEY_0 = 'http.extraHeader'
        $env:GIT_CONFIG_VALUE_0 = 'Authorization: Basic ' +
        [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$env:AZDO_PAT"))
        git clone --quiet "https://dev.azure.com/jlbalmerjr1/ClaudeTestingTerraform/_git/$name" $dest 2>&1 | Out-Null
        $env:GIT_CONFIG_COUNT = $null; $env:GIT_CONFIG_KEY_0 = $null; $env:GIT_CONFIG_VALUE_0 = $null
    }
    $fixtureOk = $true
    foreach ($name in $FixtureShas.Keys) {
        if ((git -C (Join-Path $Work $name) rev-parse HEAD).Trim() -ne $FixtureShas[$name]) { $fixtureOk = $false }
    }

    $env:PSGRAPHRENDERTOHTML_MODULE_PATH =
    Join-Path $Ecosystem 'PSGraphRenderToHtml/output/PSGraphRenderToHtml/PSGraphRenderToHtml.psd1'
    Push-Location $target
    $buildOut = & ./build.ps1 2>&1 | Out-String
    $buildExit = $LASTEXITCODE
    Pop-Location

    $regenerated = Join-Path $Work 'verify-graph.json'
    Remove-Module PSTerraformGraph -Force -ErrorAction SilentlyContinue
    Import-Module (Join-Path $target 'output/PSTerraformGraph/PSTerraformGraph.psd1') -Force
    $graph = Get-TfGraph -Path (Join-Path $Work 'TfSiteCore'), (Join-Path $Work 'TfSiteEdge'), (Join-Path $Work 'TfSiteOps')
    Export-TfGraph -Graph $graph -Path $regenerated | Out-Null

    $score = & $scorer -Path $regenerated
    $cmp = & (Join-Path $clone 'evals/tf/Compare-TfGraph.ps1') -Expected $oracle -Actual $regenerated
    $recordedGraph = Join-Path $Harness 'runs/tf-003-generalisation/graph.json'
    $identical = (Get-FileHash $regenerated -Algorithm SHA256).Hash -eq (Get-FileHash $recordedGraph -Algorithm SHA256).Hash

    # The correction note claims 7 / 7 and zero differences. Read the CLAIM from
    # the note and compare it against what was just produced, rather than
    # hard-coding the number twice.
    $note = Get-Content (Join-Path $Harness 'runs/tf-003-generalisation/README.md') -Raw
    $noteClaims = $note -match 'rescored by evals/tf/fixture2/Test-TfFixture2Case\.ps1'

    $scored = $FailCheck -eq '3' ? 6 : $score.Passed
    $ok3 = $targetSha -eq $FinalSha -and $fixtureOk -and $buildExit -eq 0 -and
    $scored -eq 7 -and $cmp.DifferenceCount -eq 0 -and $identical -and $noteClaims
    Add-Result '3 tf-003 rescore reproduced from a fresh built clone' $ok3 (
        ('sha {0}; fixtures {1}; build exit {2}; {3} / 7; {4} differences; graph {5}; note present {6}' -f
            ($targetSha -eq $FinalSha ? 'matches' : 'WRONG'),
            ($fixtureOk ? 'at their pins' : 'MOVED'),
            $buildExit, $scored, $cmp.DifferenceCount,
            ($identical ? 'byte-identical' : 'DIFFERS'), $noteClaims))
}

# ---- 4. Every number in the README generalisation section resolves ---------
# Hand-listed mapping, checked mechanically. The point is not that a regex found
# a digit: it is that each claim NAMES a file, and that file contains it.
$readme = Get-Content (Join-Path $clone 'README.md') -Raw
$section = [regex]::Match($readme, '### tf-003 — the blind run.*?(?=\n## )', 'Singleline').Value
$claims = @(
    @{ Claim = '6 / 7 first shot'; InReadme = '6 / 7'; Source = 'runs/tf-003-generalisation/README.md'; Pattern = 'functional-tf \(first-shot\):\s+6 / 7' }
    @{ Claim = '7 / 7 final'; InReadme = '7 / 7'; Source = 'runs/tf-003-generalisation/README.md'; Pattern = 'functional-tf \(final\):\s+7 / 7' }
    @{ Claim = '99 / 99 nodes'; InReadme = '99 / 99'; Source = 'plans/0037-consolidation/tf-003-rescore.txt'; Pattern = '99 / 99' }
    @{ Claim = '88 / 88 edges'; InReadme = '88 / 88'; Source = 'plans/0037-consolidation/tf-003-rescore.txt'; Pattern = '88 / 88' }
    @{ Claim = '184 first-shot differences'; InReadme = '184'; Source = 'runs/tf-003-generalisation/README.md'; Pattern = 'differences \(first-shot\):\s+184' }
    @{ Claim = '94 tf-001 first-shot differences'; InReadme = '94'; Source = 'runs/tf-003-generalisation/README.md'; Pattern = 'first-shot differences \| 94' }
    @{ Claim = '31 tf-001 final differences'; InReadme = '31'; Source = 'runs/tf-002-convention-and-case3/README.md'; Pattern = 'differences \| 31' }
    @{ Claim = 'tf-002 0 differences'; InReadme = '**0**'; Source = 'runs/tf-002-convention-and-case3/README.md'; Pattern = 'differences:\s+0' }
    @{ Claim = '1 of 3 iterations'; InReadme = '1 of 3'; Source = 'runs/tf-003-generalisation/README.md'; Pattern = 'iterations allowed / used:\s+3 / 1' }
    @{ Claim = '31 min phase 1'; InReadme = '31 min'; Source = 'runs/tf-003-generalisation/README.md'; Pattern = 'phase-1-minutes:\s+31' }
)
$unresolved = [System.Collections.Generic.List[string]]::new()
foreach ($c in $claims) {
    $inSection = $section.Contains($c.InReadme)
    $sourcePath = Join-Path $clone $c.Source
    $hasSource = (Test-Path $sourcePath) -and ((Get-Content $sourcePath -Raw) -match $c.Pattern)
    if (-not ($inSection -and $hasSource)) {
        $unresolved.Add(('{0} ({1})' -f $c.Claim, (-not $inSection ? 'not in the section' : 'not in ' + $c.Source)))
    }
}
if ($FailCheck -eq '4') { $unresolved.Add('injected by -FailCheck 4') }
Add-Result '4 every generalisation-section number resolves to an artifact' ($unresolved.Count -eq 0) (
    $unresolved.Count -eq 0 ? "$($claims.Count) / $($claims.Count) resolve" : ('unresolved: ' + ($unresolved -join '; ')))

# ---- 5. The release did not move the installed surface --------------------
$surface = & git -C $Harness diff v1.1.0..v1.1.1 --name-only -- skills/ commands/ 2>&1
$surfaceEmpty = @($surface | Where-Object { $_ }).Count -eq 0
$pluginLines = @(& git -C $Harness diff v1.1.0..v1.1.1 -U0 -- .claude-plugin/ 2>&1 |
        Where-Object { $_ -match '^[+-][^+-]' })
$allVersion = @($pluginLines | Where-Object { $_ -notmatch '^\s*[+-]\s*"version":' }).Count -eq 0
if ($FailCheck -eq '5') { $surfaceEmpty = $false }
Add-Result '5 skills/ and commands/ byte-identical; only version fields moved' ($surfaceEmpty -and $allVersion -and $pluginLines.Count -gt 0) (
    ('skills+commands diff {0}; .claude-plugin changed lines {1}, all version fields: {2}' -f
        ($surfaceEmpty ? 'empty' : 'NOT EMPTY'), $pluginLines.Count, $allVersion))

# ---------------------------------------------------------------------------
$passed = @($results | Where-Object Result -EQ 'PASS').Count
$failed = @($results | Where-Object Result -EQ 'FAIL').Count
$skipped = @($results | Where-Object Result -EQ 'SKIP').Count
Write-Host ''
Write-Host ("VERIFY: {0} passed, {1} failed, {2} skipped, of {3}   (clone {4})" -f
    $passed, $failed, $skipped, $results.Count, $cloneSha.Substring(0, 7))
if ($failed -gt 0) { exit 1 }
exit 0
